#!/bin/bash
# Copyright 1999-1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/livecd-tools/x-setup,v 1.14 2005/05/16 19:26:39 wolf31o2 Exp $

# Check for an xorg.conf
if [ ! -e /etc/X11/xorg.conf ]
then
	echo "ERROR: /etc/X11/xorg.conf cannot be found! Exiting"
	exit 1
fi

if [ -f /sbin/livecd-functions.sh ]
then
	source /sbin/livecd-functions.sh
else
	echo "ERROR: /sbin/livecd-functions.sh could not be loaded!"
	exit 1
fi

livecd_check_root || exit 1

#first, get paths right if we're getting started b4 login
source /etc/profile

livecd_get_cmdline || exit 1

for x in $CMDLINE
do
        if [ "$x" = "agpgart" ]
        then
			modprobe agpgart > /dev/null 2>&1
        fi
done

get_video_cards || exit 1

nice -20 eselect opengl set $GLTYPE


#exec /usr/bin/xinit