#!/bin/bash
# Copyright 2006 - SabayonLinux (Fabio Erculiani)
# Application: aiglx-setup - helper - enable/disable AIGLX

# Wrapper script, run "/sbin/desktop-acceleration-setup xgl"
/sbin/desktop-acceleration-setup aiglx $1