#!/bin/sh

setup_system() {

# Prepare KDM Configuration
cp /usr/kde/3.5/share/config/kdm/kdmrc /tmp/ -p
cp /root/.dmrc /tmp/ -p

# change default session
echo "[Desktop]" > /root/.dmrc
echo "Session=accel-server" >> /root/.dmrc
#AutoLoginEnable=true
sed -i 's/AutoLoginEnable=.*/AutoLoginEnable=true/' /usr/kde/3.5/share/config/kdm/kdmrc
#AutoLoginUser=sabayonuser
sed -i 's/AutoLoginUser=.*/AutoLoginUser=root/' /usr/kde/3.5/share/config/kdm/kdmrc

# to restore:
# /tmp/.dmrc --> /root/.dmrc
# /tmp/kdmrc --> /usr/kde/3.5/share/config/kdm/kdmrc

}

# Configure the Session
setup_system
