#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-db/mysql/files/mysql.init,v 1.7 2004/07/14 21:41:15 agriffis Exp $

depend() {
	need net
	use dns
}

checkconfig() {
	if [ ! -f /etc/mysql/my.cnf ] ; then
		eerror "No /etc/mysql/my.cnf file exists!"
	fi

    dir=`my_print_defaults mysqld | grep -- --datadir | sed -e "s|^.*=\(.*\)|\1|"`

	if [ ! -d $dir/mysql ] ; then
		eerror "You dont appear to have the mysql database installed yet."
		eerror "Please run /usr/bin/mysql_install_db to have this done..."
		return 1
	fi
}

start() {
	checkconfig || return 1
	ebegin "Starting mysqld"
	/usr/bin/safe_mysqld >/dev/null 2>&1 &
	eend $?
}

stop () {
	ebegin "Stopping mysqld"
	start-stop-daemon --stop --quiet \
		--pidfile=/var/run/mysqld/mysqld.pid --retry 20
	eend $?
}
