#!/bin/sh

# Fix possible problems
xhost +
rm /root/.Xauthority

# Restore Previous Configuration
mv /tmp/.dmrc /root/.dmrc
mv /tmp/kdmrc /usr/kde/3.5/share/config/kdm/

# Set wallpaper using fluxbox tool
fbsetbg -l

# Start accel-manager
nice -20 /usr/sbin/accel-manager

killall ogg123 &> /dev/null
sleep 2

touch /etc/accel-manager-exited

