#!/bin/sh
if [ -e "/usr/kde/3.5/bin/kmdr-executor" ]; then
  if [ "$UID" == "0" ]; then
     /usr/kde/3.5/bin/kmdr-executor /usr/share/accel-manager/accel-manager.kmdr
  else
     kdesu /usr/kde/3.5/bin/kmdr-executor /usr/share/accel-manager/accel-manager.kmdr
  fi
else
  echo "You need to install Kommander 3.5.x"
fi
