#!/bin/sh
# compiz-start script
#
# hacky autodetection of neccessary options for XGL/AIGLX/NVIDIA
#
# Hanno Boeck, http://www.hboeck.de/
# Fabio Erculiani, http://www.sabayonlinux.org - Sabayon Linux Project Leader
#
# Licensed under the same conditions as compiz itself (MIT or GPL)

if [ ! -x /usr/bin/glxinfo ]; then
	echo "glxinfo not found, please install mesa-progs."
	exit -1
fi

GLX_WITH_DIRECT=`glxinfo|grep -c GLX_EXT_texture_from_pixmap`
GLX_WITH_INDIRECT=`LIBGL_ALWAYS_INDIRECT=1 glxinfo|grep -c GLX_EXT_texture_from_pixmap`
GLX_RENDER=`glxinfo|grep -c "OpenGL renderer string: Mesa GLX Indirect"`


COMPIZ_OPTIONS="--replace"

if [ $GLX_WITH_DIRECT -eq 3 ]; then
	if [ $GLX_RENDER -eq 0 ]; then
		echo NVIDIA detected
		export __GL_YIELD="NOTHING"
	else
		echo XGL detected
	fi
elif [ $GLX_WITH_INDIRECT -eq 3 ]; then
	echo AIGLX detected
	export LIBGL_ALWAYS_INDIRECT=1
	COMPIZ_OPTIONS=$COMPIZ_OPTIONS" --indirect-rendering"
fi

selected_windeco="gtk-window-decorator"
if [ ! -z $KDE_FULL_SESSION ] && [ -x /usr/bin/kde-window-decorator ]; then
	echo Using KDE decorator
	selected_windeco="kde-window-decorator"
	nice -15 kde-window-decorator --replace &
else
	echo Using GTK decorator
	nice -15 gtk-window-decorator --replace &
fi

echo "Starting Compiz with: "$COMPIZ_OPTIONS
nice -15 compiz $COMPIZ_OPTIONS ini &

# Wait and see if compiz ran fine
sleep 5

processes=$(ps ax)
compiz_running=0
for process in $processes; do
	if [ "$process" == "compiz" ]; then
		compiz_running=1
	fi
done

if [ "$compiz_running" == 0 ]; then

	# shait, we need to revert back to the DE window manager

	if [ -x "/sbin/lspci" ]; then
		export lspci_cmd="/sbin/lspci"
	elif [ -x "/usr/sbin/lspci" ]; then
		export lspci_cmd="/usr/sbin/lspci"
	else
		export lspci_cmd="echo Unknown"
	fi
	current_gpu=`$lspci_cmd | grep "VGA" | cut -d "V" -f 2- | cut -d":" -f 2-`

	if [ -n "`echo $DESKTOP_SESSION | grep kde`" ]; then
		# run kwin
		`which kwin` --replace &
		dcop knotify default notify Installer_status Installer "Compiz cannot be started. Please check that you have a working and supported Video Card, OpenGL functionality or visit Sabayon Linux Support forum at: http://www.sabayonlinux.org/forum
GPU: $(echo $current_gpu)" '' '' 2 0

	else

		# run metacity
		`which metacity` --replace &
		zenity --error --text "Compiz cannot be started. Please check that you have a working and supported Video Card, OpenGL functionality or visit Sabayon Linux Support forum at:\n <u>http://www.sabayonlinux.org/forum</u>.\n\n<u>Current Graphics Processing Unit</u>\n<b>$(echo $current_gpu)</b>" --title "Compiz issues..."

	fi

else

	# start loop check
	while true; do

		sleep 3

		# check if $selected_windeco is still running, otherwise, respawn
		processes=$(ps ax)
		check_enabled=0
		for process in $processes; do
			if [ "$process" == "compiz" ]; then
				check_enabled=1
			fi
		done
		
		if [ "$check_enabled" == 1 ]; then
			windeco_running=0
			for process in $processes; do
				if [ "$process" == "$selected_windeco" ]; then
					windeco_running=1
				fi
			done
			if [ "$windeco_running" == 0 ]; then
				# respawn!
				nice -15 $selected_windeco --replace &
			fi
		else
			# we also have to respawn compiz, I know it's a dirty thing but
			# another compiz-start should take over this process
			echo "Compiz crashed - take over!"
			killall -9 compiz $selected_windeco &> /dev/null
			/usr/bin/compiz-start
		fi

	done

fi

