#!/bin/bash
# Copyright 2007 - SabayonLinux (Fabio Erculiani)
# Application: xgl-setup - helper - enable/disable XGL

# Wrapper script, run "/sbin/desktop-acceleration-setup xgl"
/sbin/desktop-acceleration-setup xgl $@
