#!/bin/sh

# We will running dropbox with the lowest prio.
ionice -c 3 -p $$ > /dev/null
renice -n 19 -p $$ > /dev/null

DISPLAY=''
workdir="$(dirname $(readlink -f $0))"
LD_LIBRARY_PATH="${workdir}:${LD_LIBRARY_PATH}"
exec ${workdir}/dropbox $@
