#!/bin/bash
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/livecd-tools/openglify,v 1.6 2005/05/31 19:08:28 wolf31o2 Exp $

#This script is designed to tweak the system for opengl-update
#set up our flexible opengl stuff:

#move symlinks to a malleable /etc/opengl directory.
install -d test/lib/modules/extensions

rm /usr/lib/libGL{,core}.{la,a,so}* > /dev/null 2>&1
rm /usr/lib32/libGL{,core}.{a,so}* > /dev/null 2>&1

rm /usr/lib/modules/extensions/libglx* > /dev/null 2>&1
rm /usr/lib32/modules/extensions/libglx* > /dev/null 2>&1
rm /usr/lib/xorg/modules/extensions/libglx* > /dev/null 2>&1
rm /usr/lib32/xorg/modules/extensions/libglx* > /dev/null 2>&1

ln -sf /etc/opengl/lib/libGL.so /usr/lib/libGL.so
ln -sf /etc/opengl/lib/libGL.so.1 /usr/lib/libGL.so.1
ln -sf /etc/opengl/lib/libGLcore.so /usr/lib/libGLcore.so
ln -sf /etc/opengl/lib/libGLcore.so.1 /usr/lib/libGLcore.so.1
ln -sf /etc/opengl/lib32/libGL.so /usr/lib32/libGL.so
ln -sf /etc/opengl/lib32/libGL.so.1 /usr/lib32/libGL.so.1
ln -sf /etc/opengl/lib32/libGLcore.so /usr/lib32/libGLcore.so
ln -sf /etc/opengl/lib32/libGLcore.so.1 /usr/lib32/libGLcore.so.1


ln -sf /etc/opengl/lib/modules/extensions/libglx.so /usr/lib/modules/extensions/libglx.so
ln -sf /etc/opengl/lib/modules/extensions/libglx.so /usr/lib/xorg/modules/extensions/libglx.so
ln -sf /etc/opengl/lib32/modules/extensions/libglx.so /usr/lib32/modules/extensions/libglx.so
ln -sf /etc/opengl/lib32/modules/extensions/libglx.so /usr/lib32/xorg/modules/extensions/libglx.so

ln -sf /etc/opengl/lib/modules/extensions/libglx.a /usr/lib/modules/extensions/libglx.a
ln -sf /etc/opengl/lib/modules/extensions/libglx.a /usr/lib/xorg/modules/extensions/libglx.a
ln -sf /etc/opengl/lib32/modules/extensions/libglx.a /usr/lib32/modules/extensions/libglx.a
ln -sf /etc/opengl/lib32/modules/extensions/libglx.a /usr/lib32/xorg/modules/extensions/libglx.a

ln -sf /etc/opengl/lib/libGL.la /usr/lib/libGL.la
ln -sf /etc/opengl/lib32/libGL.la /usr/lib32/libGL.la
