#!/bin/bash

configure_opengl() {

if [ -n "$cmdline_opengl_exists" ]; then
   for word in `cat /proc/cmdline` ; do
      case $word in
         opengl=*)
            opengl_toset=$(echo $word | cut -d "=" -f 2)
            nice -20 /usr/bin/eselect opengl set --dst-prefix=/etc/opengl $opengl_toset
            ;;
      esac
   done
else
   get_video_cards &> /dev/null
   get_current_gl=$(eselect opengl show)

   # Fix for "nVidia Corporation Unknown device"
   if [ -n "`lspci | grep VGA | grep -i nvidia | grep -i 'Unknown device'`" ]; then
      nice -20 /usr/bin/eselect opengl set --dst-prefix=/etc/opengl nvidia
   elif [ -n "`lspci | grep VGA | grep nVidia | grep 'PCI Express'`" ]; then
      # Fix for "nVidia Corporation PCI Express Device"
      nice -20 /usr/bin/eselect opengl set --dst-prefix=/etc/opengl nvidia
   else
      if [ "$get_current_gl" != "$GLTYPE" ]; then
         /usr/sbin/x-setup
      fi
   fi
fi

}

runtime_linking_proprietary_drivers() {

   # Do this only if on the system is available a NVIDIA or ATI card
   if [ -n "`lspci | grep ' VGA ' | grep -i nvidia`" ] || [ -n "`lspci | grep ' VGA ' | grep -i ati`" ]; then

      mount -t tmpfs none /lib/modules/$(uname -r)/video
      current_arch=$(uname -m)
      if [ "$current_arch" == "x86_64" ]; then
         ld_arch="elf_x86_64"
      elif [ "$current_arch" == "i686" ]; then
         ld_arch="elf_i386"
      fi
      ld -m $ld_arch -r -o /lib/modules/$(uname -r)/video/nvidia.ko /lib/nvidia/nvidia.o /lib/nvidia/nvidia.mod.o
      ld -m $ld_arch -r -o /lib/modules/$(uname -r)/video/fglrx.ko /lib/fglrx/fglrx.o /lib/fglrx/fglrx.mod.o

   fi

}

configure_read_write_paths() {

   # if it's not already mounted, mount KDM config r/w
   # but only when unionfs is not available
   if [ -z "`cat /proc/cmdline | grep -i unionfs`" ]; then
      kdm_is_mounted=$(cat /etc/mtab | grep kdm )
      if [ -z "$kdm_is_mounted" ]; then
         # mount it !
         mkdir /tmp/kdm
         cp /usr/kde/3.5/share/config/kdm/* /tmp/kdm/ -Rp
         mount -t tmpfs none /usr/kde/3.5/share/config/kdm/
         cp /tmp/kdm/* /usr/kde/3.5/share/config/kdm/ -Rp
         rm -rf /tmp/kdm
      fi
   fi

   # Fix .ICE-unix permissions - still needed ??
   mkdir -m 1777 /tmp/.ICE-unix -p
   chown root /tmp/.ICE-unix
   chown root /tmp/.ICE-unix -R
   chmod 1777 /tmp/.ICE-unix

}

configure_video_settings() {

   # X.Org must be started and now I'm checking if user wants to start the server at 640x480
   if [ -n "$cmdline_legacy_exist" ]; then
      mv -f /etc/X11/xorg.conf.legacy /etc/X11/xorg.conf
      /sbin/gpu-configuration &> /dev/null
      #echo -e "\E[33;36m * \E[0m \E[01;32m Starting up X.Org in (- Legacy -) mode ::\E[0m"
      #echo -e "\t Display Configuration: 800x600 at 60Hz"
   else

      # Probe for Hsync, Vsync, Modes and in case the user has specified
      # something else on the command line, it will be overwritten

      if [ -e "/usr/sbin/ddcxinfo-knoppix" ] && [ -z "$cmdline_noddc_exist" ]; then

          # hsync
          hsync=$(/usr/sbin/ddcxinfo-knoppix -hsync)
          if [ "$hsync" != "0-0" ]; then
              # ok, we got it
              sed -i '/HorizSync/ s/#//' /etc/X11/xorg.conf
              sed -i '/HorizSync/ s/.*/    HorizSync '$hsync'/' /etc/X11/xorg.conf
          fi

          # vsync
          vsync=$(/usr/sbin/ddcxinfo-knoppix -vsync)
          if [ "$vsync" != "0-0" ]; then
              # ok, we got it
              sed -i '/VertRefresh/ s/#//' /etc/X11/xorg.conf
              sed -i '/VertRefresh/ s/.*/    VertRefresh '$vsync'/' /etc/X11/xorg.conf
          fi

          # Modes?
          if [ "$vsync" != "0-0" ] && [ "$hsync" != "0-0" ]; then
              modes=$(/usr/sbin/ddcxinfo-knoppix -modes)
              if [ -n "$modes" ]; then
                  sed -i '/Modes/ s/#//' /etc/X11/xorg.conf
                  sed -i "/Modes/ s/.*/        $modes/" /etc/X11/xorg.conf
              fi
          fi

      fi

      if [ -n "$cmdline_resolution_forced" ];then
         # change resolution in X.Org
         for word in `cat /proc/cmdline` ; do
            case $word in
               res=*)
                  resolution_toset=$(echo $word | cut -d "=" -f 2)
		  if [ "$resolution_toset" == "800x600" ]; then
                     sed -i '/Modes/ s/"1024x768"/"'$resolution_toset'"/' /etc/X11/xorg.conf
		  elif [ "$resolution_toset" == "640x480" ]; then
                     sed -i '/Modes/ s/"1024x768"/"'$resolution_toset'"/' /etc/X11/xorg.conf
		  else
                     sed -i '/Modes/ s/"1024x768"/"'$resolution_toset'" "1024x768"/' /etc/X11/xorg.conf
		  fi
                  #echo -e "\E[33;36m * \E[0m\E[01;32m Setting X.Org to $resolution_toset if it's available \E[0m"
		  sed -i '/Modes/ s/#//' /etc/X11/xorg.conf
               ;;
            esac
         done
      fi

      # Check if refresh= is forced by cmdline
      if [ -n "$cmdline_refresh_exist" ];then
	 # change VertRefresh in X.Org
         for word in `cat /proc/cmdline` ; do
            case $word in
               refresh=*)
		  sed -i '/VertRefresh/ s/#//' /etc/X11/xorg.conf
                  refresh_toset=$(echo $word | cut -d "=" -f 2)
                  sed -i '/VertRefresh/ s/.*/    VertRefresh '$refresh_toset'/' /etc/X11/xorg.conf
		  #echo -e "\E[33;36m * \E[0m\E[01;32m Setting VertRefresh to $refresh_toset Hz \E[0m"
               ;;
            esac
         done
      fi

      # Check if refresh= is forced by cmdline
      if [ -n "$cmdline_hsync_exist" ];then
         # change HorizSync in X.Org
         for word in `cat /proc/cmdline` ; do
            case $word in
               hsync=*)
                  sed -i '/HorizSync/ s/#//' /etc/X11/xorg.conf
                  hsync_toset=$(echo $word | cut -d "=" -f 2)
                  sed -i '/HorizSync/ s/.*/    HorizSync '$hsync_toset'/' /etc/X11/xorg.conf
                  #echo -e "\E[33;36m * \E[0m\E[01;32m Setting HorizSync to $hsync_toset Hz \E[0m"
               ;;
            esac
         done
      fi


      if [ -z "$cmdline_onlyvesa_exist" ]; then
	 #echo -e "\E[33;36m * \E[0m\E[01;32m  Video Card:`lspci | grep VGA | cut -d: -f3` \E[0m"
         /sbin/gpu-configuration &> /dev/null
      fi

   fi

}

      # create seed
      rm -f /etc/x-setup-configuration-running
      touch /etc/x-setup-configuration-running

      # get livecd functions
      source /sbin/livecd-functions.sh

      # Variables
      cmdline_onlyvesa_exist=$(cat /proc/cmdline | grep onlyvesa)
      cmdline_noproprietary_exist=$(cat /proc/cmdline | grep noproprietary)
      cmdline_opengl_exists=$(cat /proc/cmdline | grep "opengl=")
      cmdline_noxorg_exist=$(cat /proc/cmdline | grep nox)
      cmdline_fastboot_exist=$(cat /proc/cmdline | grep fastboot)
      cmdline_kiosk_exist=$(cat /proc/cmdline | grep internetkiosk)
      cmdline_legacy_exist=$(cat /proc/cmdline | grep legacy)
      cmdline_resolution_forced=$(cat /proc/cmdline | grep "res=")
      cmdline_refresh_exist=$(cat /proc/cmdline | grep refresh=)
      cmdline_hsync_exist=$(cat /proc/cmdline | grep hsync=)
      cmdline_noddc_exist=$(cat /proc/cmdline | grep "noddc")
      cmdline_xgl_exist=$(cat /proc/cmdline | grep " xgl")
      cmdline_aiglx_exist=$(cat /proc/cmdline | grep " aiglx")
      cmdline_noaccelmanager_exist=$(cat /proc/cmdline | grep "noaccelmanager")

      # Prepare Video Cards Proprietary Drivers
      runtime_linking_proprietary_drivers

      # Prepare OpenGL
      if [ -z "$cmdline_onlyvesa_exist" ]; then
         configure_opengl
      fi

      # Configure Video Card Driver
      configure_video_settings

      # Configure read/write paths
      configure_read_write_paths

      # delete seed
      rm -f /etc/x-setup-configuration-running
