#!/sbin/runscript
# Copyright 2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
   need net dbus
}

start() {
   ebegin "Starting ${SVCNAME}"
   start-stop-daemon --start --exec /sbin/dhcdbd \
   	--pidfile /var/run/dhcdbd.pid \
      	-- ${DHCDBD_ARGS}
   eend $?
}

stop() {
   ebegin "Stopping ${SVCNAME}"
   start-stop-daemon --stop --exec /sbin/dhcdbd \
   	--pidfile /var/run/dhcdbd.pid
   eend $?
}
