#!/sbin/runscript
# Copyright 1999-2002 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/x11-drivers/xf86-input-synaptics/files/rc.init,v 1.1 2008/08/22 17:09:35 chainsaw Exp $

depend() {
	use localmount
}

start() {
	ebegin "Starting syndaemon"
	/usr/bin/syndaemon ${SYNDAEMON_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping syndaemon"
	kill `cat /var/run/syndaemon.pid`
	eend $?
}
