#!/bin/sh
cmd=0
if [ -z "$1" ]; then
  cmd=1
else
  if [ "$1" = "e16" ]; then
    cmd=0
  elif [ "$1" = "fluxbox" ]; then
    cmd=0
  elif [ "$1" = "gnome" ]; then
    cmd=0
  else
    cmd=1
  fi
fi

processes=$(ps auxf)
xgl_running=$(echo $processes | grep Xgl)
acceleration_enabled=$(glxinfo | grep "direct rendering" | grep -i "yes")

aquamarine_enabled=$(cat /proc/cmdline | grep aquamarine)
if [ -n "$aquamarine_enabled" ] && [ -e /usr/bin/aquamarine ];then
  window_decor="aquamarine --replace"
else
  window_decor="emerald --replace"
fi


if [ -n "$acceleration_enabled" ] || [ -n "$xgl_running" ]; then
  if [ "$cmd" = "1" ]; then
    if [ -n "$xgl_running" ]; then
      $window_decor & beryl-xgl --replace dbus settings
    else
      $window_decor & beryl --strict-binding --indirect-rendering --replace dbus settings
    fi
  fi
else
   # Notify the funny thing
   dcop knotify default notify DRI_status 'Direct Rendering' 'OpenGL acceleration is disabled. 3D Desktop cannot be loaded.' '' '' 2 0
fi
