#!/bin/sh
cmd=0
if [ -z "$1" ]; then
  cmd=1
else
  if [ "$1" = "e16" ]; then
    cmd=0
  elif [ "$1" = "fluxbox" ]; then
    cmd=0
  elif [ "$1" = "gnome" ]; then
    cmd=0
  else
    cmd=1
  fi
fi

processes=$(ps auxf)

if [ "$cmd" = "1" ]; then
  xgl_running=$(echo $processes | grep Xgl)
  if [ -n "$xgl_running" ]; then
    emerald --replace & beryl --replace --xgl-binding dbus settings
  else
    emerald --replace & beryl --strict-binding --indirect-rendering --replace dbus settings
  fi
fi
