#!/bin/bash
# Copyright 2006 - SabayonLinux (Fabio Erculiani)
# Application: aiglx-setup - helper - enable/disable AIGLX

# Constants
if [ -e "/usr/kde/3.4" ];then
    kdmdir="/usr/kde/3.4/share/config/kdm/"
elif [ -e "/usr/kde/3.5" ];then
    kdmdir="/usr/kde/3.5/share/config/kdm/"
fi
beryl_tmpdir="/tmp/"
beryl_wrapper="beryl-wrapper.desktop"
beryl_manager="beryl-manager.desktop"
beryl_wrapper_desktop_file=$beryl_tmpdir$beryl_wrapper
beryl_manager_desktop_file=$beryl_tmpdir$beryl_manager
xorg_conf="/etc/X11/xorg.conf"

if [ -z "$1" ] || [ "$1" == "--help" ]; then
   echo "aiglx-setup - SabayonLinux - Copyright 2006"
   echo
   echo -e "  This helper enable/disable AIGLX system wide."
   echo -e "  You need to pass only one argument:"
   echo -e "    disable - disable AIGLX"
   echo -e "    enable - enable AIGLX"
   echo
   exit 0
fi

if [ "$UID" != "0" ]; then
   echo "Error: you need to run this as root. Please type \"aiglx-setup --help\" for more help."
fi

if [ "$1" != "enable" ] && [ "$1" != "disable" ]; then
   echo "Error: parameter not recognized. Please type \"aiglx-setup --help\" for more help."
   exit 1
else
   if [ "$1" == "enable" ]; then
      echo -en "Enabling AIGLX system wide..."

       # Changing KDM configuration
       if [ -e "/usr/bin/AIGLX" ]; then
          # old way - not needed anymore
          sed -i 's/ServerCmd=.*/ServerCmd=\/usr\/bin\/AIGLX /' $kdmdir/kdmrc
       else
          sed -i 's/ServerCmd=.*/ServerCmd=\/usr\/bin\/X /' $kdmdir/kdmrc
       fi


	# now it's handled on /usr/kde/3.5/share/config/kdm/Xsession - after DBUS - before case $session in
        if [ -z "`cat /usr/kde/3.5/share/config/kdm/Xsession | grep beryl-wrapper`" ]; then
	   sed -i '/case $session in/ s/case $session in/\/usr\/bin\/beryl-wrapper $DESKTOP_SESSION \&\n\ncase $session in/' $kdmdir/Xsession
	fi

	# Enable AIGLX Stuff
	sed -i '/"AIGLX"/ s/#//g' $xorg_conf
        opengl_nvidia=$(eselect opengl show | grep nvidia)
        if [ -n "$opengl_nvidia" ]; then
	   sed -i '/"AddARGBGLXVisuals"/ s/#//g' $xorg_conf
        fi
	sed -i '/"Composite"/ s/#//g' $xorg_conf

	# Beryl Wrapper
	echo "[Desktop Entry]" > $beryl_wrapper_desktop_file
	echo "Name=No name" >> $beryl_wrapper_desktop_file
	echo "Encoding=UTF-8" >> $beryl_wrapper_desktop_file
	echo "Version=1.0" >> $beryl_wrapper_desktop_file
	echo "Exec=/usr/bin/beryl-wrapper" >> $beryl_wrapper_desktop_file
	echo "X-GNOME-Autostart-enabled=true" >> $beryl_wrapper_desktop_file

	# Beryl Manager
	echo "[Desktop Entry]" > $beryl_manager_desktop_file
	echo "Name=No name" >> $beryl_manager_desktop_file
	echo "Encoding=UTF-8" >> $beryl_manager_desktop_file
	echo "Version=1.0" >> $beryl_manager_desktop_file
	echo "Exec=/usr/bin/beryl-manager" >> $beryl_manager_desktop_file
	echo "X-GNOME-Autostart-enabled=true" >> $beryl_manager_desktop_file

	# Add compiz to GNOME startup - because GNOME is always special...
        for huser in `ls /home`
           do
	      if [ -d "/home/$huser" ]; then
	         if [ ! -e "/home/$huser/.config/autostart" ]; then
	            mkdir -p /home/$huser/.config/autostart &> /dev/null
		    chown $huser:users /home/$huser/.config -R &> /dev/null
	         fi
                 cp $beryl_wrapper_desktop_file /home/$huser/.config/autostart/ &> /dev/null
                 chown $huser:users /home/$huser/.config/autostart/$beryl_wrapper &> /dev/null
                 cp $beryl_manager_desktop_file /home/$huser/.config/autostart/ &> /dev/null
                 chown $huser:users /home/$huser/.config/autostart/$beryl_manager &> /dev/null
	         if [ -e "/usr/share/applications/beryl-settings.desktop" ] && [ -e "/home/$huser/Desktop" ]; then
	            cp /usr/share/applications/beryl-settings.desktop /home/$huser/Desktop/ &> /dev/null
	            chown $huser:users /home/$huser/Desktop/beryl-settings.desktop &> /dev/null
	         fi
	      fi
          done
         rm $beryl_wrapper_desktop_file
         rm $beryl_manager_desktop_file
      echo -e "Done"
   else
      echo -en "Disabling AIGLX system wide (reverting to X.Org)..."

      # Changing KDM configuration
      sed -i 's/ServerCmd=.*/ServerCmd=\/usr\/bin\/X/' $kdmdir/kdmrc
      if [ -n "`cat $kdmdir/Xsession | grep beryl-wrapper`" ]; then
	sed -i '/.*beryl-wrapper.*$DESKTOP_SESSION/d' $kdmdir/Xsession
      fi

      # Disable AIGLX Option
      sed -i '/"AIGLX"/ s/#//g' $xorg_conf
      sed -i '/"AIGLX"/ s/Option/#Option/' $xorg_conf
      opengl_nvidia=$(lspci | grep ' VGA '| grep -i nvidia)
      if [ -n "$opengl_nvidia" ]; then
         sed -i '/"AddARGBGLXVisuals"/ s/#//g' $xorg_conf
         sed -i '/"AddARGBGLXVisuals"/ s/Option/#Option/' $xorg_conf
      fi
      sed -i '/"Composite"/ s/#//g' $xorg_conf
      sed -i '/"Composite"/ s/Option/#Option/' $xorg_conf

      for file in `find /home -maxdepth 4 -name $beryl_wrapper`
         do
            rm -f $file
         done
      for file in `find /home -maxdepth 4 -name $beryl_manager`
         do
            rm -f $file
         done
      echo -e "Done"
   fi
fi
